export const skills = [
  { id: "e1", title: "Html", imgUrl: "image/skills/html.png", valueRating: 5 },
  { id: "e2", title: "Css&Sass", imgUrl: "image/skills/css.png", valueRating: 5 },
  { id: "e3", title: "Js&Js6", imgUrl: "image/skills/js.png", valueRating: 5 },
  { id: "e4", title: "Reactjs", imgUrl: "image/skills/react.png", valueRating: 4.5 },
  { id: "e5", title: "Redux", imgUrl: "image/skills/redux.png", valueRating: 4 },
  { id: "e6", title: "Git&Github", imgUrl: "image/skills/git.png", valueRating: 4 },
  { id: "e7", title: "Material Ui", imgUrl: "image/skills/material.png", valueRating: 4 },
  { id: "e8", title: "Nodejs", imgUrl: "image/skills/node.png", valueRating: 3.5 },
  { id: "e9", title: "Expressjs", imgUrl: "image/skills/express.png", valueRating: 3.5 },
  { id: "e10", title: "Axios", imgUrl: "image/skills/axios.png", valueRating: 3.5 },
  { id: "e11", title: "Tailwind", imgUrl: "image/skills/tailwind.png", valueRating: 3 },
  { id: "e12", title: "Bootstrap", imgUrl: "image/skills/bootstrap.svg", valueRating: 3 },
  // { id: "e13", title: "github", imgUrl: "image/skills/github.png", valueRating: 3 },
  // { id: "e14", title: "netlify", imgUrl: "image/skills/netlify.png", valueRating: 3 },
];
